### ISSUE TITLE
Waffentruck

### ISSUE THREAD

**Issue by Merthan5446** [Truezify/IceT-Reallife#25]
Staatsfraktionen haben nach ne zeit keine Waffen mehr und danach muss man für Geld Waffen kaufen und diese auch transportieren dieser Waffentruck kann aber von Gangs angegriffen werden und wenn die Gangs den Waffentruck gestoppt bekommen verlieren die Staatsfraktionen das Geld was sie für die Waffen bezahlt haben plus die Waffen.

**Comment by Truezify** [comment]
"Waffentruck" wird nicht bearbeitet / angenommen.
